apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdc-controller
  namespace: sdc-system
  labels:
    app.kubernetes.io/name: sdc-controller
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sdc-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sdc-controller
        sdcio.dev/data-server: "true"
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      serviceAccountName: sdc-controller
      containers:
      - name: sdc-controller
        image: input.context[0].data.sdcControllerImage
        imagePullPolicy: Always
        command:
        - /app/sdc-controller
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: "NODE_NAME"
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: "NODE_IP"
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: PPROF_PORT
          value: "8081"
        - name: REVERTIVE
          value: "true"
        - name: ENABLE_SUBSCRIPTION
          value: "true"
        - name: ENABLE_TARGET
          value: "true"
        - name: ENABLE_TARGETDATASTORE
          value: "true"
        - name: ENABLE_TARGETCONFIGSERVER
          value: "true"
        - name: ENABLE_TARGETRECOVERYSERVER
          value: "true"
        - name: ENABLE_DISCOVERYRULE
          value: "true"
        - name: ENABLE_SCHEMA
          value: "true"
        #- name: ENABLE_CONFIG
        #  value: "true"
        - name: ENABLE_CONFIGSET
          value: "true"
        - name: ENABLE_WORKSPACE
          value: "true"
        - name: ENABLE_ROLLOUT
          value: "true"
        volumeMounts:
        - name: schema-store
          mountPath: /schemas
        - name: workspace-store
          mountPath: /workspace
      - name: data-server
        image: input.context[0].data.dataServerImage
        imagePullPolicy: Always
        command:
        - /app/data-server
        args:
        - "--config=/config/data-server.yaml"
        ports:
        - name: data-service
          containerPort: 56000
        volumeMounts:
        - name: data-server-config
          mountPath: /config
        - name: cache
          mountPath: /cached/caches
        - name: schema-store
          mountPath: /schemas
        - name: schema-db
          mountPath: /schemadb
      volumes:
      - name: data-server-config
        configMap:
          name: data-server
      - name: cache
        emptyDir:
          sizeLimit: 10Gi
      - name: schema-store # yang file from git
        persistentVolumeClaim:
          claimName: pvc-schema-store
      - name: schema-db # persistent schema obj from the parsed yang files
        persistentVolumeClaim:
          claimName: pvc-schema-db
      - name: workspace-store # git workspace
        persistentVolumeClaim:
          claimName: pvc-workspace-store
